# Generated by Django 5.1.7 on 2025-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
